"""add case memory tables

Revision ID: 0106200638b9
Revises: b0661bd082e6
Create Date: 2026-07-11 02:23:50.309692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0106200638b9'
down_revision: Union[str, Sequence[str], None] = 'b0661bd082e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_facts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('fact_type', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.String(length=1000), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('supersedes_fact_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_facts_case_type', 'case_facts', ['case_id', 'fact_type'], unique=False)
    op.create_index('ix_case_facts_tenant_case', 'case_facts', ['tenant_id', 'case_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requested_relief', sa.Text(), nullable=False),
    sa.Column('amount', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claims_tenant_case', 'claims', ['tenant_id', 'case_id'], unique=False)
    op.create_table('contradictions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('contradiction_type', sa.String(length=40), nullable=False),
    sa.Column('subject_key', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('fact_ids', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_fact_id', sa.String(length=32), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('resolved_by', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contradictions_tenant_case', 'contradictions', ['tenant_id', 'case_id'], unique=False)
    op.create_table('deadlines',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('deadline_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trigger_event_id', sa.String(length=32), nullable=True),
    sa.Column('trigger_date', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.String(length=20), nullable=False),
    sa.Column('assumptions', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('confirmed_by', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deadlines_tenant_case', 'deadlines', ['tenant_id', 'case_id'], unique=False)
    op.create_table('defenses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responds_to_claim_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_defenses_tenant_case', 'defenses', ['tenant_id', 'case_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('evidence_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('supports_claim_id', sa.String(length=32), nullable=True),
    sa.Column('supports_event_id', sa.String(length=32), nullable=True),
    sa.Column('reliability_status', sa.String(length=20), nullable=False),
    sa.Column('admissibility_status', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_tenant_case', 'evidence', ['tenant_id', 'case_id'], unique=False)
    op.create_table('missing_information',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('field_key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('reason_required', sa.Text(), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('related_legal_issue', sa.String(length=200), nullable=False),
    sa.Column('expected_source', sa.String(length=40), nullable=False),
    sa.Column('completion_condition', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by_fact_id', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'field_key', name='uq_missing_info_case_field')
    )
    op.create_index('ix_missing_info_tenant_case', 'missing_information', ['tenant_id', 'case_id'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('risk_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('affected_claim', sa.String(length=200), nullable=False),
    sa.Column('supporting_reference', sa.String(length=200), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=False),
    sa.Column('related_missing_information', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risks_tenant_case', 'risks', ['tenant_id', 'case_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_date', sa.String(length=20), nullable=False),
    sa.Column('event_time', sa.String(length=12), nullable=False),
    sa.Column('is_approximate', sa.Boolean(), nullable=False),
    sa.Column('party_reference', sa.String(length=200), nullable=False),
    sa.Column('legal_significance', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_case_date', 'timeline_events', ['case_id', 'event_date'], unique=False)
    op.create_index('ix_timeline_tenant_case', 'timeline_events', ['tenant_id', 'case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_tenant_case', table_name='timeline_events')
    op.drop_index('ix_timeline_case_date', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('ix_risks_tenant_case', table_name='risks')
    op.drop_table('risks')
    op.drop_index('ix_missing_info_tenant_case', table_name='missing_information')
    op.drop_table('missing_information')
    op.drop_index('ix_evidence_tenant_case', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_defenses_tenant_case', table_name='defenses')
    op.drop_table('defenses')
    op.drop_index('ix_deadlines_tenant_case', table_name='deadlines')
    op.drop_table('deadlines')
    op.drop_index('ix_contradictions_tenant_case', table_name='contradictions')
    op.drop_table('contradictions')
    op.drop_index('ix_claims_tenant_case', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_case_facts_tenant_case', table_name='case_facts')
    op.drop_index('ix_case_facts_case_type', table_name='case_facts')
    op.drop_table('case_facts')
    # ### end Alembic commands ###
