"""add_auth_sessions_and_case_members

Revision ID: 1fecf1dd397e
Revises: b8ea3b690168
Create Date: 2026-07-05 01:12:28.273411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fecf1dd397e'
down_revision: Union[str, Sequence[str], None] = 'b8ea3b690168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_family_id', sa.String(length=64), nullable=False),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=50), nullable=False),
    sa.Column('replaced_by_session_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('ix_auth_expires', 'auth_sessions', ['expires_at'], unique=False)
    op.create_index('ix_auth_family', 'auth_sessions', ['token_family_id'], unique=False)
    op.create_index('ix_auth_user_revoked', 'auth_sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_table('case_members',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('membership_role', sa.String(length=20), nullable=False),
    sa.Column('permissions_override', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_member_case', 'case_members', ['case_id', 'user_id'], unique=False)
    op.create_index('ix_case_member_tenant', 'case_members', ['tenant_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_case_member_tenant', table_name='case_members')
    op.drop_index('ix_case_member_case', table_name='case_members')
    op.drop_table('case_members')
    op.drop_index('ix_auth_user_revoked', table_name='auth_sessions')
    op.drop_index('ix_auth_family', table_name='auth_sessions')
    op.drop_index('ix_auth_expires', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
