"""add official provider ingestion runs

Revision ID: 6352fc55db15
Revises: ce94808703a4
Create Date: 2026-07-13 06:34:36.291589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6352fc55db15'
down_revision: Union[str, Sequence[str], None] = 'ce94808703a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_ingestion_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider_code', sa.String(length=30), nullable=False),
    sa.Column('run_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('cursor_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_count', sa.Integer(), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('ingested_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('new_version_count', sa.Integer(), nullable=False),
    sa.Column('conflict_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('last_safe_error_code', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_ingestion_runs_created_at'), 'source_ingestion_runs', ['created_at'], unique=False)
    op.create_index('ix_source_ingestion_runs_provider', 'source_ingestion_runs', ['provider_code', 'created_at'], unique=False)
    op.create_table('source_ingestion_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('provider_code', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('candidate_url_hash', sa.String(length=64), nullable=False),
    sa.Column('dedupe_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_record_id', sa.String(length=32), nullable=True),
    sa.Column('source_version_id', sa.String(length=32), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('safe_error_code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['source_ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_ingestion_items_dedupe', 'source_ingestion_items', ['provider_code', 'dedupe_key'], unique=False)
    op.create_index('ix_source_ingestion_items_run', 'source_ingestion_items', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_ingestion_items_run', table_name='source_ingestion_items')
    op.drop_index('ix_source_ingestion_items_dedupe', table_name='source_ingestion_items')
    op.drop_table('source_ingestion_items')
    op.drop_index('ix_source_ingestion_runs_provider', table_name='source_ingestion_runs')
    op.drop_index(op.f('ix_source_ingestion_runs_created_at'), table_name='source_ingestion_runs')
    op.drop_table('source_ingestion_runs')
    # ### end Alembic commands ###
