"""add document pipeline tables

Revision ID: 87be64670347
Revises: 0106200638b9
Create Date: 2026-07-11 15:54:19.395569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87be64670347'
down_revision: Union[str, Sequence[str], None] = '0106200638b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_extractions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('extraction_type', sa.String(length=40), nullable=False),
    sa.Column('field_key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.String(length=1000), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('text_span', sa.String(length=80), nullable=False),
    sa.Column('source_quote_hash', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('memory_fact_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_extractions_document', 'document_extractions', ['document_id'], unique=False)
    op.create_index('ix_doc_extractions_tenant_case', 'document_extractions', ['tenant_id', 'case_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_pages_doc', 'document_pages', ['document_id', 'page_number'], unique=False)
    op.add_column('documents', sa.Column('safe_filename', sa.String(length=500), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('extension', sa.String(length=16), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('document_type_source', sa.String(length=20), nullable=False, server_default='suggested'))
    op.add_column('documents', sa.Column('analysis_status', sa.String(length=30), nullable=False, server_default='pending'))
    op.add_column('documents', sa.Column('support_level', sa.String(length=30), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('documents', sa.Column('extracted_text_available', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('documents', sa.Column('failure_code', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('uploaded_by', sa.String(length=32), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.create_index('ix_documents_tenant_case', 'documents', ['tenant_id', 'case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_tenant_case', table_name='documents')
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'uploaded_by')
    op.drop_column('documents', 'failure_code')
    op.drop_column('documents', 'extracted_text_available')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'support_level')
    op.drop_column('documents', 'analysis_status')
    op.drop_column('documents', 'document_type_source')
    op.drop_column('documents', 'extension')
    op.drop_column('documents', 'safe_filename')
    op.drop_index('ix_document_pages_doc', table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index('ix_doc_extractions_tenant_case', table_name='document_extractions')
    op.drop_index('ix_doc_extractions_document', table_name='document_extractions')
    op.drop_table('document_extractions')
    # ### end Alembic commands ###
