"""add_legal_grounds_and_claim_grounding

Revision ID: b8ea3b690168
Revises: 03050a891788
Create Date: 2026-07-04 22:57:50.778509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ea3b690168'
down_revision: Union[str, Sequence[str], None] = '03050a891788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_grounding_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('petition_hash', sa.String(length=64), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('grounding_ready', sa.Boolean(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grounding_case_hash', 'claim_grounding_snapshots', ['case_id', 'petition_hash', 'source_fingerprint'], unique=False)
    op.create_table('legal_grounds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('graph_id', sa.String(length=32), nullable=False),
    sa.Column('normalized_citation', sa.String(length=200), nullable=False),
    sa.Column('legislation_code', sa.String(length=20), nullable=False),
    sa.Column('legislation_name', sa.String(length=200), nullable=False),
    sa.Column('article', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('applicability_status', sa.String(length=30), nullable=False),
    sa.Column('temporal_status', sa.String(length=20), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'normalized_citation', name='uq_grounds_case_citation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legal_grounds')
    op.drop_index('ix_grounding_case_hash', table_name='claim_grounding_snapshots')
    op.drop_table('claim_grounding_snapshots')
    # ### end Alembic commands ###
