"""add legal source backbone tables

Revision ID: ce94808703a4
Revises: 87be64670347
Create Date: 2026-07-11 18:26:40.484480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce94808703a4'
down_revision: Union[str, Sequence[str], None] = '87be64670347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('canonical_key', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('issuing_authority', sa.String(length=200), nullable=False),
    sa.Column('court', sa.String(length=120), nullable=False),
    sa.Column('chamber', sa.String(length=120), nullable=False),
    sa.Column('case_number', sa.String(length=80), nullable=False),
    sa.Column('decision_number', sa.String(length=80), nullable=False),
    sa.Column('decision_date', sa.String(length=20), nullable=False),
    sa.Column('publication_date', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.String(length=20), nullable=False),
    sa.Column('repeal_date', sa.String(length=20), nullable=False),
    sa.Column('official_url', sa.String(length=1000), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('temporal_status', sa.String(length=20), nullable=False),
    sa.Column('current_version_id', sa.String(length=32), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_key', name='uq_source_records_canonical_key')
    )
    op.create_index('ix_source_records_status', 'source_records', ['verification_status'], unique=False)
    op.create_index('ix_source_records_type', 'source_records', ['source_type'], unique=False)
    op.create_table('source_relationships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.String(length=32), nullable=False),
    sa.Column('related_source_record_id', sa.String(length=32), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('source_version_id', sa.String(length=32), nullable=True),
    sa.Column('evidence', sa.String(length=500), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_source_record_id'], ['source_records.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_record_id', 'related_source_record_id', 'relationship_type', name='uq_source_rel_triplet')
    )
    op.create_index('ix_source_rel_record', 'source_relationships', ['source_record_id'], unique=False)
    op.create_table('source_verifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.String(length=32), nullable=False),
    sa.Column('source_version_id', sa.String(length=32), nullable=True),
    sa.Column('verification_method', sa.String(length=40), nullable=False),
    sa.Column('verifier_type', sa.String(length=20), nullable=False),
    sa.Column('verifier_user_id', sa.String(length=32), nullable=True),
    sa.Column('evidence_url', sa.String(length=1000), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_verifications_record', 'source_verifications', ['source_record_id'], unique=False)
    op.create_table('source_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.String(length=32), nullable=False),
    sa.Column('version_label', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_document_hash', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.String(length=20), nullable=False),
    sa.Column('valid_to', sa.String(length=20), nullable=False),
    sa.Column('supersedes_version_id', sa.String(length=32), nullable=True),
    sa.Column('retrieval_method', sa.String(length=40), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_record_id', 'content_hash', name='uq_source_versions_record_hash')
    )
    op.create_index('ix_source_versions_record', 'source_versions', ['source_record_id'], unique=False)
    op.create_table('source_paragraphs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_version_id', sa.String(length=32), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('heading_path', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('article_number', sa.String(length=40), nullable=False),
    sa.Column('locator_json', sa.JSON(), nullable=False),
    sa.Column('embedding_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_paragraphs_version', 'source_paragraphs', ['source_version_id', 'paragraph_index'], unique=False)
    op.create_table('source_usages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.String(length=32), nullable=False),
    sa.Column('source_version_id', sa.String(length=32), nullable=False),
    sa.Column('source_paragraph_id', sa.String(length=32), nullable=True),
    sa.Column('usage_type', sa.String(length=30), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('selected_by', sa.String(length=32), nullable=False),
    sa.Column('used_in_final_draft', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_usages_record', 'source_usages', ['source_record_id'], unique=False)
    op.create_index('ix_source_usages_tenant_case', 'source_usages', ['tenant_id', 'case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_usages_tenant_case', table_name='source_usages')
    op.drop_index('ix_source_usages_record', table_name='source_usages')
    op.drop_table('source_usages')
    op.drop_index('ix_source_paragraphs_version', table_name='source_paragraphs')
    op.drop_table('source_paragraphs')
    op.drop_index('ix_source_versions_record', table_name='source_versions')
    op.drop_table('source_versions')
    op.drop_index('ix_source_verifications_record', table_name='source_verifications')
    op.drop_table('source_verifications')
    op.drop_index('ix_source_rel_record', table_name='source_relationships')
    op.drop_table('source_relationships')
    op.drop_index('ix_source_records_type', table_name='source_records')
    op.drop_index('ix_source_records_status', table_name='source_records')
    op.drop_table('source_records')
    # ### end Alembic commands ###
